# home/modules/ui/sway/special-binds/factorio-binds.conf

set $factorio ~/games/factorio/bin/x64/factorio
set $factorio_class Factorio

bindsym $mod+shift+f exec swaymsg '[class="$factorio_class" title="Factorio"] focus' || exec $factorio
