# home/modules/ui/sway/special-binds/screenshot-binds.conf

bindsym Print exec $grim ~/Pictures/screenshots/screenshot-$(date +'%Y-%m-%d-%H%M%S').png
bindsym Shift+Print exec $grim -g "$($slurp)" ~/Pictures/screenshots/screenshot-$(date +'%Y-%m-%d-%H%M%S').png
bindsym Control+Print exec $grim -g "$($slurp)" - | wl-copy

